services:
  # Application Service
  web-app:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_PORT=8080 # Set the Vite port as an environment variable
  
  # Backend Service
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000" # Map container port 5000 to host port 5000
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1 # Ensure logs are flushed immediately